
#define END_LINE ('\n')
#define DELIM ("&&")
#define SHARP ("#")
#define GRATE ("<")
#define SPACE (" ")
#define SP_DASH_SP (" - ")

#define MINUS_ONE (-1)
#define ZERO (0)
#define ONE (1)
#define TWO (2)
#define THREE (3)

#define SEPARATOR ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
#define ERR_MSG ("error: invalid parameters ...")
#define ERR_INV_FMT ("error: invalid format ...")
#define ERR_OPEN_FILE ("error: error to open result file ...")

#define END_MSG ("log parser progress was terminated ...")
#define HELP_MSG ("logparser\n\t{destination files path} a directory name that their files, must be end with <.txt> or <.log> or <.xml> extension.\n\t{result file name} a file with arbitrary name to store result.\n\t{words file name to search} a file that should be contain one line or one character at least to search.")
#define INTRO ("R.H. Behsazan log parser 2023-08-28 v.0.0.5")
#define No_WORD ("there are no input words to search ...")

#define PRC_CHECKING (" checking ...")
#define PRC_INIT (" initialization ...")
#define PRC_CHK_WRD (" checking words to search ...")
#define PRC_GTH (" gathering files ...")
#define PRC_START (" start to search files recursively ...")
#define PRC_CLEAN (" cleaning result file ...")

#define D_END_LINE ("\n\n")
#define XML_HEADER ("<?xml version=\"1.0\" encoding=\"utf-8\" ?>")
#define SIGN ("<!--  Behsazan  -->")
#define CHECK_SIGN ("<!--behsazan-->")
#define LOG_OPEN_TAG ("<log>")
#define LOG_CLOSE_TAG ("</log>")
#define THREE_MAD ("~~~")
#define CLEAN_EXT ("_clean.xml")
#define TXT (".txt")
#define LOG (".log")
#define XML (".xml")
#define SPC4 ("    ")
#define SPC6 ("      ")

